# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('x', models.FloatField(default=0, max_length=20)),
                ('y', models.FloatField(default=0, max_length=20)),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'MapsMarker',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mapmarker',
            unique_together=set([('x', 'y')]),
        ),
    ]
